Repository ELTE-Clean/Clean-Administration-Platform, pull requests merged in 2022-06, with the labels that each got.

#80 Add Get Submissions Endpoint
  backend/routes/tasks.js
Labels: api_server

#84 Move testcases to yaml conversion and add filename to submissions
  backend/routes/tasks.js
  cleanDB/scripts/clean_db.sql
  scripts/CorrectTest.py
Labels: enhancement, api_server, Database

#90 Fix section delete and task grade endpoints
  backend/routes/sections.js
  backend/routes/tasks.js
Labels: bug, api_server

#92 Add group delete endpoint
  backend/routes/groups.js
  backend/routes/sections.js
  cleanDB/scripts/clean_db.sql
Labels: api_server

#94 Assign to Groups Through Neptun ID and Group Names
  backend/routes/groups.js
  backend/routes/users.js
Labels: bug, enhancement, api_server
